#Bias sweep parameters
channels:
- name: !!str Channel 0
  parameters:
    bias_start: !!float 0
    bias_stop: !!float 10e-3
    bias_step: !!float  0.1e-3
    vna_start: !!float 4e9
    vna_stop: !!float 8e9
    vna_power: !!float -20
    vna_points: !!int 1000
    vna_bandwidth: !!float 1000
    save_path: !!str D:IMPA
- name: !!str Channel 1
  parameters:
    bias_start: !!float 0
    bias_stop: !!float 10e-3
    bias_step: !!float  0.1e-3
    vna_start: !!float 4e9
    vna_stop: !!float 8e9
    vna_power: !!float -20
    vna_points: !!int 1000
    vna_bandwidth: !!float 1000
    save_path: !!str D:IMPA