import enum
from enum import IntEnum

CAN_ADDRESS_BITS = 10
CAN_ADDRESS_MAX = 2**CAN_ADDRESS_BITS-1
CAN_RESPONSE_BASE_ID = 0x400
CAN_BROADCAST_ID = 0

MIXER_OFFSET_DAC_RESOLUTION = 12
MIXER_OFFSET_DAC_MAX = 2**MIXER_OFFSET_DAC_RESOLUTION-1
MIXER_OFFSET_DAC_MIDDLE = 2**(MIXER_OFFSET_DAC_RESOLUTION-1)

BIAS_DAC_RESOLUTION = 16
BIAS_DAC_VREF = 3.3
BIAS_DAC_MAX = 2**BIAS_DAC_RESOLUTION-1

LO_ATT_MAX = 63
LO_ATT_STEP = 0.5


@enum.unique
class PARAM_ID(IntEnum):
    MODULE_ID       = 0
    MIXER_OFFSETS   = 1
    BIAS            = 2
    BIAS_SELECT     = 3
    LO_ATT          = 4
    LO_AMP_PWR      = 5
    MIXER_BYPASS    = 6
    RF_OUTPUT       = 7